{{- range .Values.applications }}
{{- if .github.hash }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "app.serviceName" . }}-imagepullsecrets
  namespace: {{ include "project.namespace" $ }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: vault-secret
spec:
  type: kv-v2
  mount: xquare-infra-kv
  path: ci-cd-pipeline
  destination:
    name: {{ include "app.serviceName" . }}-imagepullsecrets
    create: true
    type: kubernetes.io/dockerconfigjson
  refreshAfter: 1h
  vaultAuthRef: {{ include "app.vaultAuthRef" (dict "projectNamespace" (include "project.namespace" $) "vaultAuth" (include "project.vaultAuth" $)) }}
{{- end }}
{{- end }}
