{{- range .Values.applications }}
{{- if .github.hash }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "app.serviceName" . }}-imagepullsecrets
  namespace: {{ include "project.namespace" $ }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry-auth
spec:
  type: kv-v2
  mount: xquare-infra-kv
  path: ci/harbor
  refreshAfter: 60s
  destination:
    name: {{ include "app.serviceName" . }}-imagepullsecrets
    create: true
    type: kubernetes.io/dockerconfigjson
  vaultAuthRef: {{ include "project.namespace" $ }}/{{ $.Values.project }}-infra-vault-auth
{{- end }}
{{- end }}
