---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: github-app-pem
  namespace: {{ include "project.namespace" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
    app.kubernetes.io/component: github-auth
spec:
  type: kv-v2
  mount: xquare-kv
  path: ci/github
  refreshAfter: 60s
  destination:
    name: github-app-pem
    create: true
    transformation:
      includes:
        - app_private_key
      templates:
        privateKey.pem:
          text: "{{ `{{ get .Secrets \"app_private_key\" }}` }}"
  vaultAuthRef: {{ include "project.namespace" . }}/{{ include "project.vaultAuth" . }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: github-token
  namespace: {{ include "project.namespace" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
    app.kubernetes.io/component: github-auth
spec:
  type: kv-v2
  mount: xquare-kv
  path: ci/github
  refreshAfter: 60s
  destination:
    name: github-token
    create: true
    transformation:
      includes:
        - token
  vaultAuthRef: {{ include "project.namespace" . }}/{{ include "project.vaultAuth" . }}
