{{- $githubPrivateKey := "<path:avp/data/ci-infrastructure#app_private_key>" }}
{{- $githubToken := "<path:avp/data/ci-infrastructure#token>" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: github-app-pem
  namespace: {{ include "project.namespace" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
    app.kubernetes.io/component: github-auth
type: Opaque
data:
  privateKey.pem: "{{ $githubPrivateKey | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: {{ include "project.namespace" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
    app.kubernetes.io/component: github-auth
type: Opaque
data:
  token: "{{ $githubToken | b64enc }}"
