---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: github-app-pem
  namespace: {{ include "project.namespace" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
    app.kubernetes.io/component: vault-secret
spec:
  type: kv-v2
  mount: xquare-kv
  path: ci-infrastructure
  destination:
    name: github-app-pem
    create: true
    transformation:
      excludes:
        - token
  refreshAfter: 1h
  vaultAuthRef: {{ include "app.vaultAuthRef" (dict "projectNamespace" (include "project.namespace" .) "vaultAuth" (include "project.vaultAuth" .)) }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: github-token
  namespace: {{ include "project.namespace" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
    app.kubernetes.io/component: vault-secret
spec:
  type: kv-v2
  mount: xquare-kv
  path: ci-infrastructure
  destination:
    name: github-token
    create: true
    transformation:
      excludes:
        - privateKey.pem
  refreshAfter: 1h
  vaultAuthRef: {{ include "app.vaultAuthRef" (dict "projectNamespace" (include "project.namespace" .) "vaultAuth" (include "project.vaultAuth" .)) }}