---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: harbor-registry-credentials
  namespace: {{ include "project.namespace" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry-auth
spec:
  type: kv-v2
  mount: xquare-infra-kv
  path: ci/harbor
  refreshAfter: 60s
  destination:
    name: harbor-registry-credentials
    create: true
    type: kubernetes.io/dockerconfigjson
  vaultAuthRef: {{ include "project.namespace" . }}/{{ .Values.project }}-infra-vault-auth
