{{- range .Values.applications }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "app.serviceName" . }}-webhook-httproute
  namespace: {{ include "project.namespace" $ }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: ci-webhook-route
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      name: external-gateway
      namespace: gateway
      sectionName: http
    - group: gateway.networking.k8s.io
      name: external-gateway
      namespace: gateway
      sectionName: https
  hostnames:
    - {{ include "ci.webhookHost" $ }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /webhooks/{{ $.Values.project }}-{{ include "app.serviceName" . }}
      backendRefs:
        - name: {{ include "ci.eventSourceServiceName" . }}
          port: {{ include "ci.webhookPort" $ }}
{{- end }}