---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: harbor-registry-credentials
  namespace: {{ include "project.namespace" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
    app.kubernetes.io/component: vault-secret
spec:
  type: kv-v2
  mount: xquare-kv
  path: ci-cd-pipeline
  destination:
    name: harbor-registry-credentials
    create: true
    type: kubernetes.io/dockerconfigjson
  refreshAfter: 1h
  vaultAuthRef: {{ include "app.vaultAuthRef" (dict "projectNamespace" (include "project.namespace" .) "vaultAuth" (include "project.vaultAuth" .)) }}