---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ .Values.project }}-ci-vault-auth
  namespace: {{ include "project.namespace" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
    app.kubernetes.io/component: ci-vault-auth
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: xquare-ci
    serviceAccount: {{ .Values.project }}-ci-vault-service-account
    audiences:
      - vault
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.project }}-ci-vault-service-account
  namespace: {{ include "project.namespace" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
    app.kubernetes.io/component: ci-vault-service-account
